[install]
is_configured = 0
state = enabled
build = 1

[ui]
is_visible = 0
label = UK Open Data — Carbon Intensity & NHS A&E

[launcher]
author = Will Searle (livehybrid)
description = Modular inputs for UK Carbon Intensity + NHS England A&E open data.
version = 1.0.0

[package]
check_for_updates = false
id = TA-uk-open-data

[id]
name = TA-uk-open-data
version = 1.0.0

[triggers]
reload.ta_uk_open_data_settings = simple
reload.carbon_intensity = simple
reload.nhs_ae = simple
